services:
  trabalhoacademico:
    build: .
    image: trabalhoacademico:latest
    container_name: trabalhoacademico
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - trabalhoacademico-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: trabalhoacademico_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: trabalhoacademico
      MYSQL_USER: trabalhoacademico
      MYSQL_PASSWORD: trabalhoacademico
      MYSQL_ROOT_PASSWORD: trabalhoacademico
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - trabalhoacademico-network

  selenium:
    image: selenium/standalone-chrome
    container_name: trabalhoacademico_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - trabalhoacademico-network
    shm_size: 2gb

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: trabalhoacademico_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: trabalhoacademico
    networks:
      - trabalhoacademico-network

  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: trabalhoacademico_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      trabalhoacademico-network:
        aliases:
          - auth.local

  mailpit:
    image: axllent/mailpit:latest
    container_name: trabalhoacademico_mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface Web
    networks:
      - trabalhoacademico-network
networks:
  trabalhoacademico-network:

volumes:
  mariadb_data: